import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <h2 tw='bg-yellow-300 font-bold p-3 md:text-2xl'>
                Hi! Welcome to your first Next.js siteaaaaaaaa.
            </h2>
        </div>
    );
};

export default Home;
